"""ppt.py — Deterministic PowerPoint Presentation (.pptx) builder for KAVACH.

The assigned local LLM (reasoning role) produces a clean, structured JSON description
of the slide deck (title, slides, bullet points, multi-column cards, speaker notes),
and python-pptx compiles that JSON into a modern 16:9 widescreen presentation deck.
"""

from datetime import datetime, timezone
import json
from pathlib import Path
import re
from typing import Any, Dict, List, Optional, Union

try:
    from pptx import Presentation
    from pptx.dml.color import RGBColor
    from pptx.enum.shapes import MSO_SHAPE
    from pptx.enum.text import PP_ALIGN
    from pptx.util import Inches, Pt
    HAS_PPTX = True
except ImportError:
    HAS_PPTX = False
    Presentation = None
    RGBColor = None
    MSO_SHAPE = None
    PP_ALIGN = None
    Inches = None
    Pt = None

from backend import config
from backend.audit.logbook import log_event
from backend.engine import ollama, registry
from backend.terminal_logger import log_tool


def _log_terminal(msg: str) -> None:
    log_tool("ppt", "PPTX", msg)


DRAFT_PRESENTATION_PROMPT_TEMPLATE = """You are an executive industrial presentation designer and technical briefer for KAVACH.
Based on the topic, SOPs, or briefing request below, design a concise, high-impact PowerPoint presentation deck (3 to 6 slides).

Topic / Presentation Request:
{topic_or_content}

{sources_block}

CRITICAL RULES:
1. Return ONLY a valid JSON object matching this exact structure:
{{
  "title": "Main Presentation Title",
  "subtitle": "Subtitle or Executive Context",
  "author": "KAVACH Sovereign Operations",
  "filename_slug": "short_snake_case_name",
  "slides": [
    {{
      "layout": "title",
      "title": "Main Presentation Title",
      "subtitle": "Executive Briefing & Action Plan | Air-Gapped Industrial Operations"
    }},
    {{
      "layout": "content",
      "title": "Executive Summary & Objectives",
      "summary": "High-level contextual summary sentence for this slide.",
      "bullets": [
        "First key technical point or operational finding.",
        "Second critical procedural requirement.",
        "Third safety and compliance imperative."
      ],
      "notes": "Speaker notes for the presenter on this slide."
    }},
    {{
      "layout": "two_column",
      "title": "Current State vs Proposed Standard",
      "left_heading": "Existing Procedures",
      "left_bullets": [
        "Manual parameter logging with delayed escalation.",
        "Uncalibrated relief valves exceeding tolerance."
      ],
      "right_heading": "Mandatory KAVACH Protocol",
      "right_bullets": [
        "Automated sensor thresholds with instantaneous trip.",
        "Certified SOP adherence with strict audit trail."
      ],
      "notes": "Speaker notes comparing both sides."
    }},
    {{
      "layout": "metrics_summary",
      "title": "Key Metrics & Action Conclusion",
      "metrics": [
        {{"label": "Response Time", "value": "< 200 ms"}},
        {{"label": "Risk Classification", "value": "Tier 1 High"}},
        {{"label": "Compliance Score", "value": "99.8%"}}
      ],
      "action_items": [
        "Conduct shift-wise dry run verification weekly.",
        "Ensure local physical override levers remain illuminated and accessible."
      ],
      "notes": "Final wrap-up speaker notes."
    }}
  ]
}}

2. LAYOUTS: Valid layouts are "title", "content", "two_column", "metrics_summary".
3. Return ONLY the raw JSON object. No Markdown code fences, no conversational prose.
"""


def _sanitize_slug(name: str) -> str:
    cleaned = re.sub(r"[^\w\s-]", "", name or "presentation").strip().lower()
    return re.sub(r"[-\s]+", "_", cleaned)[:40] or "presentation"


def _clean_json_response(raw: str) -> Dict[str, Any]:
    text = (raw or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r"(\{[\s\S]*\})", text)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass

    return {
        "title": "Industrial Operations Briefing",
        "subtitle": "KAVACH Sovereign System",
        "filename_slug": "operations_briefing",
        "slides": [
            {
                "layout": "title",
                "title": "Industrial Operations Briefing",
                "subtitle": "KAVACH Autonomous Operations",
            },
            {
                "layout": "content",
                "title": "Operational Overview",
                "summary": "Key operational summary generated by KAVACH.",
                "bullets": ["System status: Operational", "Zero external network dependency"],
            },
        ],
    }


def draft_presentation(
    topic_or_content: str,
    sources: Optional[List[Union[str, dict]]] = None,
    model: Optional[str] = None,
) -> Dict[str, Any]:
    """Uses the assigned LLM to produce a structured JSON blueprint for the presentation."""
    resolved_model = model or registry.get_model("reasoning")
    _log_terminal(f"Drafting presentation deck structure with model '{resolved_model}'...")

    sources_block = ""
    if sources:
        names = [s.get("filename", str(s)) if isinstance(s, dict) else str(s) for s in sources]
        sources_block = f"Available Sources:\n" + "\n".join(f"- {name}" for name in names)

    prompt = DRAFT_PRESENTATION_PROMPT_TEMPLATE.format(
        topic_or_content=topic_or_content,
        sources_block=sources_block,
    )

    raw_response = ollama.generate(resolved_model, prompt)
    structured = _clean_json_response(raw_response)

    if not structured.get("slides") or not isinstance(structured["slides"], list):
        structured["slides"] = [
            {
                "layout": "title",
                "title": structured.get("title", "Operations Briefing"),
                "subtitle": structured.get("subtitle", "KAVACH Industrial Platform"),
            },
            {
                "layout": "content",
                "title": "Executive Summary",
                "bullets": [topic_or_content[:200] if topic_or_content else "Operational briefing details."],
            },
        ]

    return structured


def _set_slide_background(slide, prs, bg_color: RGBColor) -> None:
    """Draws a full-bleed solid background rectangle to reliably color the 16:9 slide."""
    bg_shape = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, prs.slide_height
    )
    bg_shape.fill.solid()
    bg_shape.fill.fore_color.rgb = bg_color
    bg_shape.line.fill.background()
    # Send to back by moving shape element to first position in spTree
    slide.shapes._spTree.remove(bg_shape._element)
    slide.shapes._spTree.insert(2, bg_shape._element)


def render_pptx(presentation_data: Dict[str, Any]) -> Path:
    """Deterministically compiles structured presentation JSON into a 16:9 widescreen .pptx file."""
    config.OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

    title = presentation_data.get("title", "Presentation")
    slug = _sanitize_slug(presentation_data.get("filename_slug") or title)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    file_path = config.OUTPUTS_DIR / f"{slug}_{timestamp}.pptx"

    prs = Presentation()
    # Configure 16:9 Widescreen dimensions
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    blank_layout = prs.slide_layouts[6]  # Blank slide layout

    # Color Palette: Dark Navy Executive Industrial Theme
    COLOR_BG = RGBColor(15, 23, 42)          # #0F172A
    COLOR_CARD = RGBColor(30, 41, 59)        # #1E293B
    COLOR_CYAN = RGBColor(56, 189, 248)      # #38BDF8
    COLOR_GOLD = RGBColor(245, 158, 11)      # #F59E0B
    COLOR_TEXT_MAIN = RGBColor(255, 255, 255) # #FFFFFF
    COLOR_TEXT_MUTED = RGBColor(203, 213, 225)# #CBD5E1

    slides_data = presentation_data.get("slides", [])

    for s_idx, s_info in enumerate(slides_data):
        slide = prs.slides.add_slide(blank_layout)
        _set_slide_background(slide, prs, COLOR_BG)

        layout_type = (s_info.get("layout") or "content").lower()
        slide_title = s_info.get("title", "Slide")

        # Set speaker notes if available
        notes_text = s_info.get("notes")
        if notes_text:
            notes_slide = slide.notes_slide
            notes_tf = notes_slide.notes_text_frame
            notes_tf.text = str(notes_text)

        # ----------------------------------------------------
        # LAYOUT: Title Slide
        # ----------------------------------------------------
        if layout_type == "title" or s_idx == 0:
            # Decorative top brand badge
            badge_box = slide.shapes.add_textbox(Inches(1.0), Inches(1.5), Inches(11.333), Inches(0.5))
            btf = badge_box.text_frame
            btf.word_wrap = True
            bp = btf.paragraphs[0]
            bp.text = "🛡️ KAVACH SOVEREIGN OPERATIONS — EXECUTIVE BRIEFING"
            bp.font.size = Pt(12)
            bp.font.bold = True
            bp.font.color.rgb = COLOR_CYAN

            # Title Box
            title_box = slide.shapes.add_textbox(Inches(1.0), Inches(2.2), Inches(11.333), Inches(2.0))
            ttf = title_box.text_frame
            ttf.word_wrap = True
            tp = ttf.paragraphs[0]
            tp.text = slide_title
            tp.font.size = Pt(38)
            tp.font.bold = True
            tp.font.color.rgb = COLOR_TEXT_MAIN

            # Subtitle
            sub_text = s_info.get("subtitle") or presentation_data.get("subtitle") or "Confidential Operational Summary"
            sub_box = slide.shapes.add_textbox(Inches(1.0), Inches(4.5), Inches(11.333), Inches(1.2))
            stf = sub_box.text_frame
            stf.word_wrap = True
            sp = stf.paragraphs[0]
            sp.text = sub_text
            sp.font.size = Pt(18)
            sp.font.color.rgb = COLOR_TEXT_MUTED

            # Cyan accent line at bottom
            line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(1.0), Inches(6.0), Inches(11.333), Inches(0.05))
            line.fill.solid()
            line.fill.fore_color.rgb = COLOR_CYAN
            line.line.fill.background()

        # ----------------------------------------------------
        # LAYOUT: Content Slide with Structured Card Box
        # ----------------------------------------------------
        elif layout_type == "content":
            # Slide Header
            header_box = slide.shapes.add_textbox(Inches(0.9), Inches(0.6), Inches(11.5), Inches(0.9))
            htf = header_box.text_frame
            htf.word_wrap = True
            hp = htf.paragraphs[0]
            hp.text = slide_title
            hp.font.size = Pt(26)
            hp.font.bold = True
            hp.font.color.rgb = COLOR_TEXT_MAIN

            # Accent underline
            line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.9), Inches(1.5), Inches(2.0), Inches(0.04))
            line.fill.solid()
            line.fill.fore_color.rgb = COLOR_CYAN
            line.line.fill.background()

            # Optional summary sentence
            summary = s_info.get("summary")
            content_top = 1.8
            if summary:
                sum_box = slide.shapes.add_textbox(Inches(0.9), Inches(1.7), Inches(11.5), Inches(0.6))
                stf = sum_box.text_frame
                stf.word_wrap = True
                sp = stf.paragraphs[0]
                sp.text = summary
                sp.font.size = Pt(14)
                sp.font.italic = True
                sp.font.color.rgb = COLOR_GOLD
                content_top = 2.4

            # Main Card Box
            card = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.9), Inches(content_top), Inches(11.533), Inches(6.6 - content_top)
            )
            card.fill.solid()
            card.fill.fore_color.rgb = COLOR_CARD
            card.line.color.rgb = RGBColor(51, 65, 85)

            # Bullets inside Card
            bullets = s_info.get("bullets", [])
            tb = slide.shapes.add_textbox(Inches(1.2), Inches(content_top + 0.3), Inches(11.0), Inches(6.0 - content_top))
            tf = tb.text_frame
            tf.word_wrap = True

            for b_idx, b_text in enumerate(bullets):
                p = tf.paragraphs[0] if b_idx == 0 else tf.add_paragraph()
                p.text = f"•  {b_text}"
                p.font.size = Pt(16)
                p.font.color.rgb = COLOR_TEXT_MAIN
                p.space_after = Pt(14)

        # ----------------------------------------------------
        # LAYOUT: Two Column Comparison Slide
        # ----------------------------------------------------
        elif layout_type == "two_column":
            # Header
            header_box = slide.shapes.add_textbox(Inches(0.9), Inches(0.6), Inches(11.5), Inches(0.9))
            htf = header_box.text_frame
            htf.word_wrap = True
            hp = htf.paragraphs[0]
            hp.text = slide_title
            hp.font.size = Pt(26)
            hp.font.bold = True
            hp.font.color.rgb = COLOR_TEXT_MAIN

            line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.9), Inches(1.5), Inches(2.0), Inches(0.04))
            line.fill.solid()
            line.fill.fore_color.rgb = COLOR_CYAN
            line.line.fill.background()

            # Left Card
            col_width = Inches(5.6)
            col_height = Inches(4.8)

            left_card = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.9), Inches(1.8), col_width, col_height
            )
            left_card.fill.solid()
            left_card.fill.fore_color.rgb = COLOR_CARD
            left_card.line.color.rgb = RGBColor(51, 65, 85)

            # Left Content
            left_tb = slide.shapes.add_textbox(Inches(1.1), Inches(2.0), Inches(5.2), Inches(4.4))
            ltf = left_tb.text_frame
            ltf.word_wrap = True
            lp_head = ltf.paragraphs[0]
            lp_head.text = s_info.get("left_heading", "Parameters / Findings")
            lp_head.font.size = Pt(18)
            lp_head.font.bold = True
            lp_head.font.color.rgb = COLOR_GOLD
            lp_head.space_after = Pt(12)

            for b_text in s_info.get("left_bullets", []):
                lp = ltf.add_paragraph()
                lp.text = f"•  {b_text}"
                lp.font.size = Pt(14)
                lp.font.color.rgb = COLOR_TEXT_MAIN
                lp.space_after = Pt(10)

            # Right Card
            right_card = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE, Inches(6.8), Inches(1.8), col_width, col_height
            )
            right_card.fill.solid()
            right_card.fill.fore_color.rgb = COLOR_CARD
            right_card.line.color.rgb = COLOR_CYAN

            # Right Content
            right_tb = slide.shapes.add_textbox(Inches(7.0), Inches(2.0), Inches(5.2), Inches(4.4))
            rtf = right_tb.text_frame
            rtf.word_wrap = True
            rp_head = rtf.paragraphs[0]
            rp_head.text = s_info.get("right_heading", "Mandatory Directives")
            rp_head.font.size = Pt(18)
            rp_head.font.bold = True
            rp_head.font.color.rgb = COLOR_CYAN
            rp_head.space_after = Pt(12)

            for b_text in s_info.get("right_bullets", []):
                rp = rtf.add_paragraph()
                rp.text = f"✓  {b_text}"
                rp.font.size = Pt(14)
                rp.font.color.rgb = COLOR_TEXT_MAIN
                rp.space_after = Pt(10)

        # ----------------------------------------------------
        # LAYOUT: Metrics & Summary Slide
        # ----------------------------------------------------
        elif layout_type == "metrics_summary":
            # Header
            header_box = slide.shapes.add_textbox(Inches(0.9), Inches(0.6), Inches(11.5), Inches(0.9))
            htf = header_box.text_frame
            htf.word_wrap = True
            hp = htf.paragraphs[0]
            hp.text = slide_title
            hp.font.size = Pt(26)
            hp.font.bold = True
            hp.font.color.rgb = COLOR_TEXT_MAIN

            line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.9), Inches(1.5), Inches(2.0), Inches(0.04))
            line.fill.solid()
            line.fill.fore_color.rgb = COLOR_GOLD
            line.line.fill.background()

            metrics = s_info.get("metrics", [])
            m_count = min(len(metrics), 3) or 1
            box_width = Inches(11.533 / m_count - 0.2)

            # Metric Callout Boxes
            for m_i, m_item in enumerate(metrics[:3]):
                box_left = Inches(0.9 + m_i * (11.533 / m_count))
                m_card = slide.shapes.add_shape(
                    MSO_SHAPE.ROUNDED_RECTANGLE, box_left, Inches(1.8), box_width, Inches(1.8)
                )
                m_card.fill.solid()
                m_card.fill.fore_color.rgb = COLOR_CARD
                m_card.line.color.rgb = COLOR_CYAN

                m_tb = slide.shapes.add_textbox(box_left + Inches(0.1), Inches(1.9), box_width - Inches(0.2), Inches(1.6))
                mtf = m_tb.text_frame
                mtf.word_wrap = True

                vp = mtf.paragraphs[0]
                vp.text = str(m_item.get("value", "100%"))
                vp.font.size = Pt(28)
                vp.font.bold = True
                vp.font.color.rgb = COLOR_CYAN
                vp.alignment = PP_ALIGN.CENTER

                lp = mtf.add_paragraph()
                lp.text = str(m_item.get("label", "Metric"))
                lp.font.size = Pt(13)
                lp.font.color.rgb = COLOR_TEXT_MUTED
                lp.alignment = PP_ALIGN.CENTER

            # Action items bottom card
            act_card = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.9), Inches(3.9), Inches(11.533), Inches(2.7)
            )
            act_card.fill.solid()
            act_card.fill.fore_color.rgb = COLOR_CARD
            act_card.line.color.rgb = RGBColor(51, 65, 85)

            act_tb = slide.shapes.add_textbox(Inches(1.2), Inches(4.1), Inches(11.0), Inches(2.3))
            atf = act_tb.text_frame
            atf.word_wrap = True
            ahead = atf.paragraphs[0]
            ahead.text = "Immediate Operational Takeaways & Signoff"
            ahead.font.size = Pt(16)
            ahead.font.bold = True
            ahead.font.color.rgb = COLOR_GOLD
            ahead.space_after = Pt(8)

            for a_text in s_info.get("action_items", s_info.get("bullets", [])):
                ap = atf.add_paragraph()
                ap.text = f"▶  {a_text}"
                ap.font.size = Pt(14)
                ap.font.color.rgb = COLOR_TEXT_MAIN
                ap.space_after = Pt(8)

        # Fallback layout
        else:
            header_box = slide.shapes.add_textbox(Inches(0.9), Inches(0.6), Inches(11.5), Inches(0.9))
            htf = header_box.text_frame
            hp = htf.paragraphs[0]
            hp.text = slide_title
            hp.font.size = Pt(26)
            hp.font.bold = True
            hp.font.color.rgb = COLOR_TEXT_MAIN

            bullets = s_info.get("bullets", [])
            tb = slide.shapes.add_textbox(Inches(1.0), Inches(1.8), Inches(11.333), Inches(5.0))
            tf = tb.text_frame
            tf.word_wrap = True
            for b_idx, b_text in enumerate(bullets):
                p = tf.paragraphs[0] if b_idx == 0 else tf.add_paragraph()
                p.text = f"•  {b_text}"
                p.font.size = Pt(16)
                p.font.color.rgb = COLOR_TEXT_MAIN
                p.space_after = Pt(12)

    prs.save(str(file_path))
    _log_terminal(f"Successfully compiled PowerPoint presentation -> {file_path.name}")
    return file_path


def write_presentation(
    prompt: str,
    sources: Optional[List[Union[str, dict]]] = None,
    task_id: Optional[str] = None,
    model: Optional[str] = None,
) -> Dict[str, Any]:
    """High-level end-to-end tool to draft, layout, and save a .pptx presentation deck."""
    structured = draft_presentation(prompt, sources=sources, model=model)
    file_path = render_pptx(structured)
    filename = file_path.name

    slides_count = len(structured.get("slides", []))

    log_event(
        task_id=task_id,
        event_type="write",
        actor="ppt_tool",
        summary=f"Rendered PowerPoint presentation '{structured.get('title')}' ({slides_count} slides) -> {filename}",
        metadata={
            "filename": filename,
            "file_path": str(file_path),
            "title": structured.get("title"),
            "slides_count": slides_count,
        },
        external_calls=0,
    )

    return {
        "success": True,
        "title": structured.get("title", "Presentation Deck"),
        "filename": filename,
        "file_path": str(file_path),
        "download_url": f"/download/{filename}",
        "slides_count": slides_count,
        "subtitle": structured.get("subtitle", ""),
    }
