"""writer.py — Deterministic Word document (.docx) builder (Phase 5).

The LLM produces a clean, structured JSON description of the document's content,
and python-docx deterministically renders that JSON into a styled .docx file.

Phase 5 Anti-Hallucination Guard:
If the topic was not found in the Knowledge Vault (is_grounded=False), the model
is strictly instructed to write an honest notice stating the SOP does not exist in
the knowledge base, completely preventing disguised hallucinations.
"""

from datetime import datetime, timezone
import json
from pathlib import Path
import re
from typing import Any, Dict, List, Optional, Union

import docx
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor

from backend import config
from backend.audit.logbook import log_event
from backend.engine import ollama, registry

DRAFT_PROMPT_TEMPLATE = """You are a technical documentation writer. Based on the topic, context, and sources below, generate a clean, structured JSON outline for a formal document.

Topic / Content:
{topic_or_content}

{sources_block}

{grounding_directive}

You MUST return ONLY a valid JSON object matching this exact structure:
{{
  "title": "Short descriptive document title",
  "sections": [
    {{
      "heading": "Section Heading",
      "body": "Detailed technical body text for this section."
    }}
  ],
  "sources": ["source_filename_1", "source_filename_2"]
}}

Rules:
1. Return ONLY the raw JSON object. Do not include markdown code fences, prose, or explanations.
2. Structure the document with 2 to 4 comprehensive sections.
3. If sources are provided and grounded, list their exact filenames in the "sources" array.
"""


def _sanitize_filename(name: str) -> str:
    """Sanitizes a string for use as a cross-platform safe filename."""
    s = re.sub(r"[^\w\s-]", "", name).strip()
    s = re.sub(r"[-\s]+", "_", s)
    return s[:40] or "Document"


def _parse_draft_json(
    raw: str,
    fallback_title: str,
    default_sources: Optional[List[str]] = None,
    is_grounded: bool = True,
) -> Dict[str, Any]:
    """Robustly parses model output into structured document JSON with prompt-leak guards."""
    text = (raw or "").strip()

    # Strip markdown code fences if present
    fence_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if fence_match:
        text = fence_match.group(1)
    else:
        brace_match = re.search(r"(\{.*\})", text, re.DOTALL)
        if brace_match:
            text = brace_match.group(1)

    parsed = None
    try:
        parsed = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        pass

    valid_sources_set = set(default_sources or [])

    if isinstance(parsed, dict) and "title" in parsed and "sections" in parsed:
        # Guard 1: Filter prompt example title
        title_val = str(parsed.get("title", "")).strip()
        if not title_val or title_val.lower() in {
            "short descriptive document title",
            "document title",
            "title",
        }:
            parsed["title"] = fallback_title

        # Guard 2: Filter prompt example sections
        clean_sections = []
        for s in parsed.get("sections", []):
            if isinstance(s, dict):
                h = str(s.get("heading", "")).strip()
                b = str(s.get("body", "")).strip()
                if h.lower() == "section heading" and "detailed technical body text" in b.lower():
                    continue
                clean_sections.append({"heading": h or "Section", "body": b})
        parsed["sections"] = clean_sections if clean_sections else [
            {"heading": "Overview", "body": text if text else "Document content generated by KAVACH."}
        ]

        # Guard 3: Filter prompt example sources
        if not is_grounded:
            parsed["sources"] = []
        else:
            raw_sources = parsed.get("sources", [])
            filtered_sources = []
            for src in raw_sources:
                src_str = str(src).strip()
                if re.match(r"^source_filename_\d+$", src_str, re.IGNORECASE):
                    continue
                # Retain only sources that were actually retrieved
                if valid_sources_set and src_str in valid_sources_set:
                    filtered_sources.append(src_str)
            parsed["sources"] = filtered_sources if filtered_sources else (default_sources or [])

        return parsed

    # Fallback structure if JSON extraction fails
    return {
        "title": fallback_title,
        "sections": [
            {
                "heading": "Summary & Overview",
                "body": text if text else "Document content generated by KAVACH.",
            }
        ],
        "sources": default_sources if is_grounded else [],
    }


def draft_document(
    topic_or_content: str,
    sources: Optional[List[Union[str, Dict[str, Any]]]] = None,
    is_grounded: bool = True,
) -> Dict[str, Any]:
    """Asks the reasoning specialist model to draft structured document JSON."""
    reasoning_model = registry.get_model("reasoning")

    # Format sources block
    source_filenames: List[str] = []
    sources_text_lines: List[str] = []
    if sources and is_grounded:
        for s in sources:
            if isinstance(s, dict):
                fn = s.get("filename", "Unknown Source")
                excerpt = s.get("excerpt", "")
                source_filenames.append(fn)
                sources_text_lines.append(f"- [{fn}]: {excerpt}")
            else:
                fn = str(s)
                source_filenames.append(fn)
                sources_text_lines.append(f"- {fn}")

    sources_block = ""
    if sources_text_lines:
        sources_block = "Available Reference Sources:\n" + "\n".join(sources_text_lines)

    if not is_grounded:
        grounding_directive = (
            "CRITICAL TRUTHFULNESS & ANTI-HALLUCINATION RULE:\n"
            "The requested topic was NOT found in the organization's Knowledge Vault / SOPs.\n"
            "You MUST state clearly in the document title and body sections that NO procedure or documentation "
            "exists in the Knowledge Vault for this topic. Do NOT invent procedures or repurpose unrelated facts. "
            "The document must serve as an honest notice that the requested procedure is unrecorded/missing."
        )
    else:
        grounding_directive = "Ensure all technical statements are directly grounded in the provided sources and context."

    prompt = DRAFT_PROMPT_TEMPLATE.format(
        topic_or_content=topic_or_content,
        sources_block=sources_block,
        grounding_directive=grounding_directive,
    )

    try:
        raw_reply = ollama.generate(reasoning_model, prompt)
    except Exception as exc:
        raw_reply = f"Error during model generation: {exc}"

    structured = _parse_draft_json(
        raw_reply,
        fallback_title="Notice: Information Not Documented" if not is_grounded else "Technical Summary Note",
        default_sources=source_filenames if is_grounded else [],
        is_grounded=is_grounded,
    )

    return structured


def render_docx(structured_content: Dict[str, Any]) -> Path:
    """Deterministically turns structured JSON into a styled .docx file."""
    title = structured_content.get("title", "Technical Note").strip()
    sections = structured_content.get("sections", [])
    sources = structured_content.get("sources", [])

    doc = docx.Document()

    # Set page margins
    sections_doc = doc.sections
    for s in sections_doc:
        s.top_margin = Inches(1.0)
        s.bottom_margin = Inches(1.0)
        s.left_margin = Inches(1.0)
        s.right_margin = Inches(1.0)

    # Title: Heading 1 style with distinctive color
    title_p = doc.add_heading(level=1)
    title_run = title_p.add_run(title)
    title_run.font.size = Pt(22)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(20, 50, 90)  # Dark Navy
    title_p.paragraph_format.space_after = Pt(4)

    # Metadata timestamp line
    utc_now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    meta_p = doc.add_paragraph()
    meta_run = meta_p.add_run(f"Generated by KAVACH — {utc_now_str}")
    meta_run.font.size = Pt(9)
    meta_run.font.italic = True
    meta_run.font.color.rgb = RGBColor(100, 116, 139)  # Slate Gray
    meta_p.paragraph_format.space_after = Pt(18)

    # Document Sections
    for sec in sections:
        heading_text = sec.get("heading", "Section").strip()
        body_text = sec.get("body", "").strip()

        h_p = doc.add_heading(level=2)
        h_run = h_p.add_run(heading_text)
        h_run.font.size = Pt(13)
        h_run.font.bold = True
        h_run.font.color.rgb = RGBColor(30, 41, 59)
        h_p.paragraph_format.space_before = Pt(12)
        h_p.paragraph_format.space_after = Pt(4)

        b_p = doc.add_paragraph()
        b_run = b_p.add_run(body_text)
        b_run.font.size = Pt(10.5)
        b_p.paragraph_format.space_after = Pt(10)
        b_p.paragraph_format.line_spacing = 1.15

    # References section (if sources provided)
    if sources:
        ref_heading = doc.add_heading(level=2)
        ref_run = ref_heading.add_run("References & Sources")
        ref_run.font.size = Pt(13)
        ref_run.font.bold = True
        ref_run.font.color.rgb = RGBColor(30, 41, 59)
        ref_heading.paragraph_format.space_before = Pt(16)
        ref_heading.paragraph_format.space_after = Pt(4)

        for src in sources:
            src_str = src.get("filename") if isinstance(src, dict) else str(src)
            p = doc.add_paragraph(style="List Bullet")
            r = p.add_run(src_str)
            r.font.size = Pt(10)
            p.paragraph_format.space_after = Pt(2)

    # Construct filename and save to OUTPUTS_DIR
    sanitized_title = _sanitize_filename(title)
    timestamp_suffix = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"{sanitized_title}_{timestamp_suffix}.docx"
    file_path = config.OUTPUTS_DIR / filename

    doc.save(str(file_path))
    return file_path


def write_document(
    topic_or_content: str,
    sources: Optional[List[Union[str, Dict[str, Any]]]] = None,
    is_grounded: bool = True,
    task_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Orchestrates draft generation and docx rendering, and logs the write audit event."""
    structured = draft_document(topic_or_content, sources=sources, is_grounded=is_grounded)
    file_path = render_docx(structured)

    title = structured.get("title", "Technical Document")

    log_event(
        task_id=task_id,
        event_type="write",
        actor="writer",
        summary=f"Generated document '{title}' -> {file_path.name} (grounded={is_grounded})",
        metadata={
            "title": title,
            "filename": file_path.name,
            "file_path": str(file_path),
            "sources_used": structured.get("sources", []),
            "sections_count": len(structured.get("sections", [])),
            "grounded": is_grounded,
        },
        external_calls=0,
    )

    return {
        "file_path": str(file_path),
        "filename": file_path.name,
        "title": title,
        "structured_content": structured,
        "grounded": is_grounded,
    }
